image: 'node:14.16.1-alpine3.13'

stages:
  - ci

cache:
  paths:
    - node_modules/

ci:
  stage: ci
  only:
    - branches
    - pushes
  except:
    - lokalize
    - /^lokalise-.*$/
  script:
    - npm install
    - npm run eslint
