image: 'node:14.16.1-alpine3.13'

stages:
  - ci
  - deploy

cache:
  paths:
    - node_modules/

ci:
  stage: ci
  only:
    - branches
    - pushes
  except:
    - lokalize
    - /^lokalise-.*$/
  script:
    - npm install
    - npm run eslint

deploy:
  stage: deploy
  only:
    - /^release/zws-.*$/
    - /^release/fnx-.*$/
    - /^release/dio-.*$/
    - master
  script:
    - apk --no-cache add curl
    - SBRANCH=`echo $CI_COMMIT_TITLE | awk -F "'" '{print $2}'`
    - echo $SBRANCH
    - curl -k -X POST "http://mqa%40mati.io:119bfbad75b47f27fa9fc58317b454a7e6@jenkins-bb.mati.io/job/WebApps-deployment/job/deploy-all/buildWithParameters?PROJECT=${CI_PROJECT_NAME}&BRANCH=${CI_COMMIT_REF_NAME}&USER_EMAIL=${GITLAB_USER_EMAIL}&USER_NAME=${GITLAB_USER_NAME}&SRC_BRANCH=${SBRANCH}"

