image: 'node:14.16.1-alpine3.13'

stages:
  - lint

lint:
  stage: lint
  only:
    - branches
    - pushes
  except:
    - lokalize
    - /^lokalise-.*$/
  script:
    - npm ci
    - npm run lint:typecheck
    - npm run lint:eslint
