# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:8.9.4

pipelines:

  branches:
    master:
      - step:
          name: Build
          deployment: production
          caches:
            - node
          script:
            - yarn
            - yarn upgrade mgi-ui-components
            - yarn build
          artifacts:
            - build/**
      - step:
          name: Deploy to S3
          image: atlassian/pipelines-awscli
          script:
            - sed -i -e "s/mgi-dashboard-invalidation/mgi-dashboard-invalidation-$(date +%FT%T)/g" invbatch.json
            - aws s3 sync --delete --acl public-read build s3://io.mati.staging.mgi-dashboard
            - aws cloudfront create-invalidation --region us-west-2 --distribution-id E3SBBQ1P1YP0EG --invalidation-batch file://invbatch.json
