# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:8.10.0

pipelines:

  branches:
    master:
      - step:
          name: Build
          deployment: production
          caches:
            - node
          script:
            - yarn
            - yarn build:production
            - curl 'http://apiuser:P8qSGrw9XX7T@jenkins.mati.io/job/WebApps-deployment/job/mgi-dashboard-production/build?token=dmd7wc752gfd0cjdmd987dcmenvesf'
    develop:
      - step:
          name: Build & deploy
          deployment: staging
          caches:
            - node
          script:
            - yarn
            - yarn build:staging
            - curl 'http://apiuser:P8qSGrw9XX7T@jenkins.mati.io/job/WebApps-deployment/job/mgi-dashboard-staging/build?token=dndhc752gfd0cjdcysdgfwdvskjdg8ujdemf'
