# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:8.9.4

pipelines:

  branches:
    master:
      - step:
          name: Build
          deployment: production
          caches:
            - node
          script:
            - yarn
            - yarn build:production
          artifacts:
            - build/**
      - step:
          name: Deploy to S3
          image: atlassian/pipelines-awscli
          script:
            - sed -i -e "s/mgi-dashboard-invalidation/mgi-dashboard-invalidation-$(date +%FT%T)/g" invbatch.json
            - aws s3 sync --delete --acl public-read build s3://mgi.webapps/dashboard/production/
            - aws cloudfront create-invalidation --region us-east-1 --distribution-id E2KAQDZKSAY41M --invalidation-batch file://invbatch.json
    develop:
      - step:
          name: Build
          deployment: staging
          caches:
            - node
          script:
            - yarn
            - yarn build:staging
          artifacts:
            - build/**
      - step:
          name: Deploy to S3
          image: atlassian/pipelines-awscli
          script:
            - sed -i -e "s/mgi-dashboard-invalidation/mgi-dashboard-invalidation-$(date +%FT%T)/g" invbatch.json
            - aws s3 sync --delete --acl public-read build s3://mgi.webapps/dashboard/staging/
            - aws cloudfront create-invalidation --region us-west-2 --distribution-id E26BZYPCK2NWND --invalidation-batch file://invbatch.json
      - step:
          name: Run test on Jenkins
          script:
            - curl 'http://apiuser:P8qSGrw9XX7T@jenkins.mati.io/job/QA/job/Dashboard-GlobalID-staging-test/build?token=mduyfdc63d9fj34fijer87vywfmfvdvydsgrea0f4emf'
