import { makeStyles } from '@material-ui/core/styles';

export const useStyles = makeStyles((theme) => ({
  modal: {
    width: '65vw',
    maxHeight: '75vh',
    backgroundColor: theme.palette.common.black7,
    borderRadius: 5,
    overflowY: 'auto',
    overflowX: 'hidden',
    '&::-webkit-scrollbar': {
      height: 5,
      width: 5,
    },
    '&::-webkit-scrollbar-track': {
      backgroundColor: 'transparent',
    },
    '&::-webkit-scrollbar-corner': {
      backgroundColor: 'transparent',
    },
    '&::-webkit-scrollbar-thumb': {
      backgroundColor: theme.palette.common.black7,
      borderRadius: 10,
    },
  },
  modalTitle: {
    fontWeight: 700,
    fontSize: 36,
    marginBottom: 15,
  },
  modalHeader: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  modalHeaderLeft: {
    display: 'flex',
    flexDirection: 'column',
    maxWidth: '50%',
  },
  modalHeaderRight: {
    display: 'flex',
    flexDirection: 'row',
    maxWidth: '50%',
    width: '100%',
    marginRight: 20,
    paddingLeft: 30,
  },
  modalSubtitle: {
    maxWidth: 475,
    color: theme.palette.common.black75,
    fontWeight: 700,
    fontSize: 18,
    wordBreak: 'break-all',
  },
  galleryContainer: {
    overflow: 'hidden',
    flexDirection: 'row',
    flexWrap: 'nowrap',
    display: 'flex',
    scrollBehavior: 'smooth',
  },
  templateContainer: {
    display: 'inline-block',
    borderRadius: '5px',
    backgroundColor: theme.palette.common.white,
    filter: 'border: 1,5px solid rgba(80, 125, 237, 1)',
    minWidth: '220px',
    minHeight: '156px',
    maxWidth: '220px',
    maxHeight: '156px',
    marginRight: '16px',
  },
  templateCardTitle: {
    fontSize: 18,
    fontWeight: 400,
  },
  description: {
    fontSize: 12,
    fontWeight: 400,
    color: theme.palette.common.black75,
  },
  descriptionContainer: {
    height: '70px',
    overflow: 'hidden',
  },
  controlsContainer: {
    position: 'absolute',
    zIndex: 99999,
    width: '100%',
    height: '160px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingLeft: '8px',
    paddingRight: '8px',
  },
  navigationControl: {
    borderRadius: '60px',
    backgroundColor: theme.palette.common.lightblue,
    width: '51px',
    height: '51px',
    cursor: 'pointer',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
  },
  navigationControlHidden: {
    opacity: 0,
  },
  swiper: {
    width: '100%',
    height: '100%',
    paddingBottom: '8px',
    display: 'flex',
  },
  swiperTitle: {
    paddingTop: '38px',
    fontSize: 15,
    fontWeight: 400,
    color: theme.palette.common.black75,
    marginBottom: 10,
  },
  swiperSlide: {
    borderRadius: '5px',
    backgroundColor: theme.palette.common.white,
    filter: 'border: 1,5px solid rgba(80, 125, 237, 1)',
    minWidth: '220px',
    minHeight: '156px',
    maxWidth: '220px',
    maxHeight: '156px',
  },
}));
