export const VerificationPatternTypes = {
  AgeValidation: 'age-check',
  BolivianOep: 'bolivian-oep-validation',
  ChileanRegistroCivil: 'chilean-registro-civil-validation',
  ColombianRegistraduria: 'colombian-registraduria-validation',
  CostaRicanTse: 'costa-rican-tse-validation',
  ArgentinianDni: 'argentinian-dni-validation',
  ArgentinianRenaper: 'argentinian-renaper-validation',
  EcuadorianRegistroCivil: 'ecuadorian-registro-civil-validation',
  HonduranRnp: 'honduran-rnp-validation',
  ParaguayanRcp: 'paraguayan-rcp-validation',
  PeruvianReniec: 'peruvian-reniec-validation',
  SalvadorianTse: 'salvadorian-tse-validation',
  PanamenianTribunalElectoral: 'panamenian-tribunal-electoral-validation',
  Biometrics: 'biometrics',
  ProofOfOwnership: 'proof-of-ownership',
  IpValidation: 'ip-validation',
  DuplicateUserValidation: 'duplicate-user-detection',
  ComplyAdvantageValidation: 'comply-advantage-validation',
  PremiumAmlWatchlistsCheck: 'premium-aml-watchlists-search-validation',
};
