import { makeStyles } from '@material-ui/core/styles';

export const useStyles = makeStyles((theme) => ({
  templateCardTitle: {
    fontSize: 16,
    fontWeight: 500,
    lineHeight: '19px',
    color: theme.palette.common.black90,
    wordWrap: 'break-word',
  },
  cardContainer: {
    position: 'relative',
    zIndex: 100,
  },
  description: {
    fontWeight: 400,
    color: theme.palette.common.black75,
  },
  descriptionContainer: {
    height: '56px',
    lineHeight: '14px',
    fontSize: 12,
    wordWrap: 'break-word',
    marginTop: '3px',
    overflow: 'hidden',
    display: '-webkit-box',
    '-webkit-line-clamp': 4,
    '-webkit-box-orient': 'vertical',
    textOverflow: 'ellipsis',
  },
  boxContainer: {
    height: 35,
  },
  iconsContainer: {
    display: 'flex',
    flexWrap: 'wrap',
    flexDirection: 'row',
    height: '72px',
    width: '100%',
    margin: '4px 0 0 0',
  },
  iconBorder: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    boxSizing: 'border-box',
    maxWidth: '27px',
    minWidth: '27px',
    maxHeight: '27px',
    minHeight: '27px',
    margin: '4px 9px 4px 0',
    border: `1px solid ${theme.palette.common.whiteblue}`,
    borderRadius: '50%',
    background: theme.palette.common.whiteblue,
  },
  icon: {
    strokeWidth: 1.5,
    width: 22,
    height: 22,
    color: theme.palette.common.lightblue,
  },
  helperText: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 12,
    color: theme.palette.common.black75,
  },
  templateCard: {
    boxSizing: 'border-box',
    width: '252px',
    height: '186px',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'space-around',
    boxShadow: `4px 4px 4px ${theme.palette.common.lightgrayopacity}`,
  },
  cardHovered: {
    border: `1.5px solid ${theme.palette.common.lightblue}`,
    borderRadius: 5,
    opacity: 0.2,
  },
  selectButton: () => ({
    position: 'absolute',
    right: '16px',
    bottom: '16px',
    cursor: 'pointer',
    minWidth: '64px',
    minHeight: '25px !important',
    maxWidth: '64px',
    maxHeight: '25px',
    marginTop: '10px',
    color: theme.palette.common.white,
    background: theme.palette.common.lightblue,
    boxSizing: 'border-box',
    borderRadius: '12.5px',
    '&:hover, &:focus': {
      color: theme.palette.common.white,
      border: `1.5px solid ${theme.palette.common.lightblue}`,
      background: theme.palette.common.lightblue,
    },
  }),
  arrow: {
    color: theme.palette.common.black,
    left: '10px !important',
  },
  tooltip: {
    backgroundColor: theme.palette.common.black,
    borderRadius: '6px',
    left: '50%',
    fontFamily: 'Lato',
    fontStyle: 'normal',
    fontWeight: 'normal',
    fontSize: '12px',
    lineHeight: '14px',
    color: theme.palette.common.white,
    width: '220px',
  },
}));
